### ISSUE TITLE
Can you give a sample of how the data needs to be provided to the component?

### ISSUE THREAD

**Issue by cromieent** [shallinta/material-ui-tree#10]
I've been looking at this component and it looks promising for my use case, but I'm not exactly sure how the data is supposed to look coming into the Tree component.  The docs say to default to an empty object, but I would like to have default data in there.

Also, from what I can tell, it looks like the github data is coming in ordered in your example code.  Does order matter when the tree is built, or can you have random order and still have the items grouped under the repeated parent?  It looks like you're using recursion in your sample code - but not sure of the structure of your sample data.  What keys are needed in the data prop to get a properly rendered tree?

TIA!

**Comment by shallinta** [comment]
Data is just your tree data, no matter what structure it is. If you are confused about this, you can open the demo and add some `console.log` to the code to see what the final data is like.

Here I give an example data to show you how this works. 
```javascript
const data = {
  category: 'A',
  name: 'a',
  children: [
    {
      category: 'A-1',
      name: 'a-1'
    }, {
      category: 'A-2',
      name: 'a-2',
      children: [
        {
          category: 'A-2-1',
          name: 'a-2-1'
        }
      ]
    }
  ]
}
```

With this data, you can set `labelName="category"` to the tree, and it will show category at the tree node. If you want to show both category and name at the tree node, you can set `renderLabel` function to the tree, node data like `{ category: 'A-2-1', name: 'a-2-1' }` will be passed to you in arguments in this function.

**Comment by shallinta** [comment]
The key `children` can also be changed. For example, I change the key `children` to `subcategories`, and I need to modify children key name by setting `childrenName="subcategories"` to the tree at the same time.
