### ISSUE TITLE
Upgrading material-ui version?

### ISSUE THREAD

**Issue by chrisshaddad** [shallinta/material-ui-tree#13]
Any plans for upgrading material-ui version?

**Comment by shallinta** [comment]
Thank you for your issue first.

No doubt that this is a hell need. Unfortunately, I'am now trapped in angular and rxjs. 😂
There is a refactor plan to this component with react above v16.8 which we can make full use of react hooks. I will then upgrade version of material-ui when I begin to do it.

If you would like, fork this and upgrade version of material-ui in advance, then launch a pull request.

**Comment by shallinta** [comment]
See the next branch: https://github.com/shallinta/material-ui-tree/tree/next

And a v2.0.0-alpha.* version has been published to npm.
Try `npm install --save material-ui-tree@next` and help to find bugs. Thank you :).

**Comment by shallinta** [comment]
> See the next branch: https://github.com/shallinta/material-ui-tree/tree/next
> 
> And a v2.0.0-alpha.* version has been published to npm.
> Try `npm install --save material-ui-tree@next` and help to find bugs. Thank you :).

Now it's a formal version. 
```sh
npm install --save material-ui-tree@latest
```
