### ISSUE TITLE
How to log selected parent node data?

### ISSUE THREAD

**Issue by christanfoden** [shallinta/material-ui-tree#14]
Hi shallinta,

Firstly thank you for the work you have put into this I was able to build an amazing nice looking tree in no time. The issue I have is in console logging the parent node data when selected from the tree. 

If I use `getActionsData` or `renderLabel` It displays all items key value pairs in the tree not the selected one.

If `requestChildrenData` is called it calls the selected which is great but it doesn't trigger if it is a parent node.

Is there something I'm missing?

**Comment by christanfoden** [comment]
ah ok just found the onClick in the return array of `getActionsData`!! :)

**Comment by shallinta** [comment]
I didn't quite understand about your problem. Fortunately you have found a way.
It seems that the `path` in callback arguments and the util function may help. You can look into the demo code in the documentation if you need.
Welcome to try the next beta version and give feedback if there is any problems.
