### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Diyorbek** [shallinta/material-ui-tree#18]
Hello! Great library!

But I noticed that there is no `@types/material-ui-tree` package. As I am writing my project in typescript, the compiler is throwing errors about declaration files and implicit `any` types. 
Would be great adding type declaration files.

 Thanks.

**Comment by shallinta** [comment]
I will add the type declaration file as soon as possible.

**Comment by shallinta** [comment]
Supported at version 2.1.0.
