### ISSUE TITLE
e.spacing is not a function | in example

### ISSUE THREAD

**Issue by riorinald** [shallinta/material-ui-tree#26]
I open codesandsbox example in the latest version. it seems to have an issue with Material UI styling.
i can't preview the working example code.

https://codesandbox.io/s/94wyyw992r?fontsize=14
![image](https://user-images.githubusercontent.com/41993762/79415681-32ca3e80-7fd8-11ea-93b4-444fc7b3b464.png)

Also how to change `getTreeLeafDataByIndexArray` to newer version parameter?

**Comment by nuzz78** [comment]
This is easy fixed. All that changed is, material-ui have moved useStyles from material-ui/styles to material-ui/core/styles. That needs to be fixed in both styles.js and tree-node.js for it to work again.

**Comment by shallinta** [comment]
This is fixed by v2.2.1.

> Also how to change `getTreeLeafDataByIndexArray` to newer version parameter?

Use this util function, see README.md
`getNodeDataByPath:: (object, array, string) -> object.`
And the code `src/util.js` is easy to read.
