### ISSUE TITLE
Pass event when action button is pushed 

### ISSUE THREAD

**Issue by nuzz78** [shallinta/material-ui-tree#27]
In some situations its useful to get the event when an action button is pushed for a leaf of the tree (for example if you want to raise a menu from there).

Can you please change the getBtnClickHandler in tree-node.js to do this? Just need to change line 51 to have onBtnClick(e)

**Comment by shallinta** [comment]
Sure. I will do this.

**Comment by shallinta** [comment]
Fix it in v2.2.3
