### ISSUE TITLE
React 16.13.0 Hooks Error

### ISSUE THREAD

**Issue by mrefaie** [shallinta/material-ui-tree#28]
When I do use the package with React 16.13.0, I got error in used hooks. See the demo:
https://codesandbox.io/s/material-ui-treenext-demo-e3p4c

**Comment by shallinta** [comment]
What if you choose the same version of `react` as `react-dom`, like 16.13.1 ?

**Comment by mrefaie** [comment]
It is working fine with `react` 16.13.1 and `react-dom` 16.13.1 but not with `react` 16.13.0 and `react-dom` 16.13.0. For some reasons I want to use `material-ui-tree` in my `react` 16.13.0 project.

**Comment by shallinta** [comment]
This is confusing...  There is not many changes in `react-dom` 16.13.1 except bugs fixing for Suspense API. And no change log about `react` 16.13.1. Maybe you will try upgrading your `react` to 16.31.1? This will probably not crash your project I think.

**Comment by diegopamio** [comment]
The same is happening with react@17.0.1 (latest)

**Comment by shahidify** [comment]
Same hooks error with react@17.0.1. Any clue how to fix it?
Thanks.

**Comment by amitsingh0542** [comment]
@shallinta hooks error with react@17.0.1. Any fix is available for this issue?? 
Thanks in advance.

**Comment by meticoeus** [comment]
Still seeing this in react 16.14.0 also.

**Comment by shallinta** [comment]
Sorry the fix comes too late.
Upgrade to v2.2.4 and try. I hope I did fix it.
Just moved dependencies to peerDependencies to avoid version conflicts. So don't forget to install those peer dependencies.

**Comment by meticoeus** [comment]
Just tested the new version with react 16.14.0 and it's working now : )
