### ISSUE TITLE
Replace HTTP request with CURL request

### ISSUE THREAD

**Issue by bruciebruce** [shallinta/material-ui-tree#32]
Hello,

First of all great work!  This is not an issue.  I am looking to replace your https request that you make here:

    data: {
      path: "material-ui-tree",
      type: "tree",
      sha: "b3d36479a033ed6296c34fdf689d5cdbcf7a0136",
      url:
        "https://api.github.com/repos/shallinta/material-ui-tree/git/trees/next"
    }

with something that might look like this:

    data: {
      path: "material-ui-tree",
      type: "tree",
      sha: "b3d36479a033ed6296c34fdf689d5cdbcf7a0136",
      url: "curl http://localhost:9200/my-elasticsearch-index/_doc/_search?pretty=true"
}

I do not know enough yet to determine if this is possible.  Any help is greatly appreciated.  Thank you!

**Comment by shallinta** [comment]
The `url` filed here is just a URL string, but nothing about how to request to it. The component doesn't care about how you use the data and the url in data. You can request to this url through xhr2 or fetch or some else tools you like in your code. 

However, this is a browser component. I don't think you can use the cURL tool in browser cause it is a client URL tool anyway.

**Comment by bruciebruce** [comment]
Hi, Thanks for getting back.  I was able to use curl from the browser like this:

const curl = require("curl");

      curl.getJSON(elastic_url,function(err, response, d){
        let hits = d.hits.hits
        let obj = hits[0]
        let sourceObj = obj._source
      });

(not sure of the correct syntax because it is now modified).

Thanks again!

**Comment by shallinta** [comment]
wow, that's cool!
