### ISSUE TITLE
Component doesn't re-render with status changing 

### ISSUE THREAD

**Issue by EXPEakhasawneh** [shallinta/material-ui-tree#5]
I'm using `material-ui-tree` component to list some files & directories and used `getTreeLeafActionsData` function to make a search in within the list. It works! but then cannot get the list back when I delete my search query. 

I'm filtering the `children` array in within render function, so it supposes to render the whole list again if made any change on the state. 

Could you point me the right way to do it if I'm wrong?

**Comment by shallinta** [comment]
Glad to see this!
I guess you may put an InputField at a tree root and it collects your input to filter its children. Then you delete your input but its children didn't come back. So you must change text in the component state when you trigger `onChange` on the InputField. Yes it will render again if everything goes well when you delete input. 
I suggest you do some logging in your render function, like before filtering or after filtering, and to see if render function trggered when you delete input, and to see if the data array you passed to the tree children is correct after filtering. Or you may paste some codes here for more help. I am glad to help!

**Comment by EXPEakhasawneh** [comment]
Actually, I did exactly as you mentioned minus the input field not necessarily to be within the tree root, I have another input field based on it I use it as **data** after manipulating based on search query. I logged state in the main render component-which include the tree & search components- and the data returned as expected.

**Comment by shallinta** [comment]
Could you show me some critical code? Or write a demo which is similar to this case at sites like [CodeSandbox](https://codesandbox.io/)? I didn't find any problems through your description.

**Comment by shallinta** [comment]
https://codesandbox.io/s/wkp03p2jrl

Here is a demo I created to show how to insert or delete a tree node in a tree. Maybe you can find some useful code to solve your problem according to this demo code.

**Comment by EXPEakhasawneh** [comment]
https://codesandbox.io/s/3r6rpoo36m

I modified your demo, you could see search field above material tree component. Search based on file names and give me your feedback

**Comment by shallinta** [comment]
Well, when you modify `data.tree` directly in render function, you change the date in state, resulting in losing origin data. When you get data by `const { data } = this.state;`, this `data` is just a reference to `this.state.data`. Once you modify this data, you modify this.state.data. You should not modify state directly. You can do like this:
```javascript
const { data } = this.state;
const curData = Object.assign({}, data);
curData.tree = curData.tree.filter(() => { /* ... */ });
// ...
```

This works perfectly in your case. And code demo is here: https://codesandbox.io/s/r5p6lzwr9m

**Comment by EXPEakhasawneh** [comment]
Many thanks, didn't know about variable desconstructor in JS, while if you logged data each time it shows them correctly without any modificiation
