### ISSUE TITLE
Instead of icon beside the tree object I need some kind of text box/dropDown  is that possible ?

### ISSUE THREAD

**Issue by somilkhandelwalwork** [shallinta/material-ui-tree#8]

**Comment by somilkhandelwalwork** [comment]
If I add the dropdown with proper width provided, it collapses  
![image](https://user-images.githubusercontent.com/40453353/49783246-33e1c080-fd3f-11e8-88e0-00a7e3ac5534.png)

**Comment by shallinta** [comment]
Don't do this in action icon place, cause this icon will be a child of a MUI button component. You are able to put a "dropdown" component in `renderLabel` and add a `onClick` listener to this "dropdown" to avoid the tree collapsing by calling `e.stopPropagation()`.
