### ISSUE TITLE
in getActionsData() everything it returns always wrapped by a <button>tag 

### ISSUE THREAD

**Issue by somilkhandelwalwork** [shallinta/material-ui-tree#9]
In the below mention code I want to render TextField next to Leaf element of the tree since the below code is working on chrome but not in Firefox, I dig more and found that textField is wrapped by a button tag so it violates the HTML rules .Reference-> https://stackoverflow.com/questions/33420402/file-input-field-inside-button-doesnt-work-in-firefox. Please give one more tag apart from **label** and **icon** which doesn't contain wrapper as a button 
```
return [
          {
            label: <TextField id={chdIndex.join(',')} style={{ marginLeft: 10 }} defaultValue={this.props.mdhJsonpr.tree[parseInt(chdIndex[0])].url.tree[parseInt(chdIndex[1])].url.tree[parseInt(chdIndex[2])].mappingValue} />,
            hint: "Map to Headers",
             onBlur: (event) => {
               const parent = getTreeLeafDataByIndexArray(
                 data, chdIndex,
                 "tree"
               );
               console.log(parent)
               let mapping = event.target.value
               this.props.onMapping(event.target.value, chdIndex, mapping)
               if (event.target.value === "") {
                 this.props.onDeleteIcon(chdIndex)
               }
             }
          },
```

**Comment by shallinta** [comment]
Add your `TextField` in `renderLabel` function where you can return multiple components within a container or an array. And then, make your leaf text align to left and TextField align to right through styles. The `getActionsData` function is only to add buttons.
